name: Cron Scrape
on:
  schedule:
    - cron: '0 20 * * 3'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Cron Scrape
        run: |
          curl --request POST \
          --url 'https://naparcsearch.com/api/scrape' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'